### ISSUE TITLE
React Dev Tools

### ISSUE THREAD

**Issue by Daronspence** [contentful/create-contentful-extension#65]
Hello 👋 

I'm pretty new to React so forgive me if this is the wrong place for this, but I'm trying to use React Dev Tools with a Contentful CLI extension and coming up short. 

I've done some googling and tried to add this to the `index.html` file
```html
<script> __REACT_DEVTOOLS_GLOBAL_HOOK__ = parent.__REACT_DEVTOOLS_GLOBAL_HOOK__ </script>
```
However, that triggers
```
Uncaught DOMException: Blocked a frame with origin "https://localhost:1234" from accessing a cross-origin frame.
    at https://localhost:1234/:5:53
(anonymous) @ (index):5
```
Within Contentful. Surely there must be a way to use React Dev Tools for a CLI extension?

Thanks for the guidance!

**Comment by Jwhiles** [comment]
Hey Daron, it's actually a bit tricky to use the dev tools in this case because apps are run inside an IFrame. There's an explanation of how it can be done on [this issue](https://github.com/facebook/react-devtools/issues/57) but we are unlikely to support it by default, as it requires disabling some browser security features.
